### ISSUE TITLE
Couldn't Import Some Dictionaries First

### ISSUE THREAD

**Issue by Sponge-bink** [mr-pennyworth/alfred-better-dictionaries#27]
I noticed that some dictionaries couldn't be imported if no dictionaries were imported before. Like some dictionaries I converted using [PyGlossary](https://github.com/ilius/pyglossary). 

Alfred debugger says:

```
03:13:10.329] Better Dictionaries[Script Filter] Passing output '/Users/x/Library/Dictionaries/広辞苑（第七版）.dictionary' to Run Script
[03:13:14.209] ERROR: Better Dictionaries[Run Script] Traceback (most recent call last):
  File "BetterDict.py", line 451, in <module>
  File "BetterDict.py", line 331, in import_dict
  File "BetterDict.py", line 362, in start_search_server
FileNotFoundError: [Errno 2] No such file or directory: '/Users/x/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts/db.log'
[40511] Failed to execute script 'BetterDict' due to unhandled exception!
[03:13:14.222] Better Dictionaries[Run Script] Processing complete
[03:13:14.224] Better Dictionaries[Run Script] Passing output '' to Post Notification
```

When that happens I checked, `/Users/x/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts/db.log'` truly wasn't there.

But If I import a dictionary, say, an Apple built-in dictionary, first, then that dictionary can be imported successfully.

**Comment by mr-pennyworth** [comment]
Thanks @Sponge-bink for the bug report, I have identified the issue and fixed it: 6cf3c2aefcc4daee72d0b8c9a6a512c1addd9c77

Latest release: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.9
