### ISSUE TITLE
Error Importing Dictionary - Multidictionnaire de la langue francaise

### ISSUE THREAD

**Issue by makzsslm** [mr-pennyworth/alfred-better-dictionaries#28]
I get an error while importing the following french dictionary:

`Multidictionnaire de la langue francaise`

```
ERROR: Better Dictionaries[Run Script] Traceback (most recent call last):
  File "urllib3/connection.py", line 196, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 495, in _make_request
  File "urllib3/connection.py", line 398, in request
  File "http/client.py", line 1331, in endheaders
  File "http/client.py", line 1091, in _send_output
  File "http/client.py", line 1035, in send
  File "urllib3/connection.py", line 236, in connect
  File "urllib3/connection.py", line 211, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10a9c2300>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=6789): Max retries exceeded with url: /indexes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a9c2300>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "meilisearch/_httprequests.py", line 53, in send_request
  File "requests/api.py", line 115, in post
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=6789): Max retries exceeded with url: /indexes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a9c2300>: Failed to establish a new connection: [Errno 61] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "BetterDict.py", line 451, in <module>
  File "BetterDict.py", line 338, in import_dict
  File "BetterDict.py", line 151, in build_index
  File "BetterDict.py", line 382, in create_index
  File "meilisearch/client.py", line 79, in create_index
  File "meilisearch/index.py", line 145, in create
  File "meilisearch/_httprequests.py", line 77, in post
  File "meilisearch/_httprequests.py", line 64, in send_request
meilisearch.errors.MeilisearchCommunicationError: MeilisearchCommunicationError, HTTPConnectionPool(host='127.0.0.1', port=6789): Max retries exceeded with url: /indexes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a9c2300>: Failed to establish a new connection: [Errno 61] Connection refused'))
[36319] Failed to execute script 'BetterDict' due to unhandled exception!
```

Seems to be something to do with indexing.

**Comment by mr-pennyworth** [comment]
Thanks for the bug report @makzsslm!
Based on the error messages, it looks like somehow the `alfred-dict-server` program included in the workflow directory wasn't running. I'm not sure why it wasn't running :(

When I tried to import the same dictionary, it was imported without an issue. I would recommend `.dict-factory-reset` to clean up all previous imports (including failed ones) and trying again. Also, to figure out whether the problem is with the dictionary or somewhere else, if the french dictionary fails, can you try importing "New Oxford American Dictionary" and see if that works?

**Comment by makzsslm** [comment]
Mmm that's strange, on my end "Oxford Dictionary of English" (and some others) works, but not "Multidictionnaire". 
HTML pages are being generated in the `Workflow Data` folder, but it hangs before starting the indexing.

Tried:
- after a factory reset
- after factory reset and installing the Oxford
- on a fresh install of the workflow

When rerunning the install after the first time I get this error:

```
Traceback (most recent call last):
  File "BetterDict.py", line 451, in <module>
  File "BetterDict.py", line 337, in import_dict
  File "BetterDict.py", line 122, in create_html_files
FileExistsError: [Errno 17] File exists: '/Users/XXXXX/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.05FA6EC7-B067-4037-85C4-83F1596A6AF2/dict-entry.css' -> '/Users/XXXXX/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts/com-apple-dictionary-fr-Multi/html/dict-entry.css'
```

**Comment by mr-pennyworth** [comment]
strange! looks like somehow the cleanup didn't work correctly :(
the error message is saying the file `'/Users/XXXXX/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts/com-apple-dictionary-fr-Multi/html/dict-entry.css'
` already exists. However, factory reset should have deleted the entire folder `'/Users/XXXXX/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts'`

One way to get around this problem would be to manually delete that folder and try again.

**Comment by makzsslm** [comment]
Right, but that is equivalent to a fresh install of the workflow - i get the first error again.

**Comment by mr-pennyworth** [comment]
> Right, but that is equivalent to a fresh install of the workflow - i get the first error again.
Sorry I'm confused. Can you help me disambiguate the above?
1. Since it is equivalent to a fresh install, *I will* get the first error again (so, I haven't tried).
2. It is equivalent to a fresh install. I tried, and *I did* get the first error again.

**Comment by makzsslm** [comment]
Sorry for the confusion. I did get this error, following these steps:

- Uninstalled the workflow by right clicking in Alfred preferences
- Made sure the folder located at `/Users/XXXX/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4ADE52B3-63E8-48E5-8AB6-72C54AC52B1C` had been deleted correctly
- Deleted the folder located at `/Users/XXXX/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts`
- Dowloaded a fresh install of the workflow
- Ran the setup, waited a bit (no confirmation make it tricky to know when it's done)
- Ran the install script
- Got the first error

**Comment by mr-pennyworth** [comment]
Thanks @makzsslm!
That was super helpful! With these steps, I was able to get the same error on my machine as well.
